INSERT INTO `aes`.`tb_tip`
(`description`,
`title`)
VALUES
("Beba um copo de água ou um refrigerante após cada dose de bebida alcoólica. Você sentirá menos vontade de beber.", "Dica 1"),
("Nunca beba direto da  garrafa. Dessa forma, você não consegue controlar o quanto está bebendo.", "Dica 2"),
("Você quer parar de beber? Peça às pessoas para não lhe oferecer bebidas alcoólicas", "Dica 3"),
("Beba sempre em pequenos goles. Isso fará com que você beba menos. ", "Dica 4"),
("Não há nada de errado em recusar uma bebida alcoólica! Lembre-se disso…", "Dica 5"),
("Decida o número máximo de doses que vai  tomar por semana - Siga a sua meta para alcançar melhores resultados.", "Dica 6"),
("Decida onde você vai beber e onde não irá. Decidir isso de antemão aumenta as suas chances de evitar problemas. ", "Dica 7"),
("Fique sem beber bebidas alcoólicas por pelo menos 2 dias por semana. Isso diminui o hábito de beber e ajuda o seu organismo a se recuperar.", "Dica 8"),
("o seu copo está pela metade, faça uma pausa e pare de beber por 15 minutos. Você perceberá que vai beber menos utilizando esta estratégia", "Dica 9"),
("Sempre que começar a sentir vontade de beber comece a fazer algo divertido que não envolva álcool. Com o tempo você irá beber menos. ", "Dica 10"),
("Não beba álcool quando você se sentir triste ou com raiva. O consumo de bebidas pode contribuir para piorar os seus problemas.", "Dica 11"),
("Se estiver tomando medicamentos, considere não beber - a maioria deles interage com o álcool, podendo ter efeitos perigosos para o seu organismo.", "Dica 12"),
("Se você sentir um forte desejo de beber, converse com um alguém que possa ajudar. Você se beneficiará ao compartilhar os seus sentimentos e pensamentos.", "Dica 13"),
("Tente mudar seu estilo de vida, evitando beber e aumentando hábitos saudáveis. A sua saúde irá melhorar, aumentando a sua qualidade de vida.", "Dica 14"),
("Comunique a seus amig@s a sua decisão de reduzir a frequência e quantidade de consumo de – el@s podem ajudar a manter sua decisão não oferecendo bebidas a você.", "Dica 15"),
("As pessoas gostam e se admiram ao saber que alguém está tentando ser mais saudável.  Não sinta vergonha de dizer que está reduzindo seu consumo de álcool, pensando em sua saúde.", "Dica 16"),
("Procure estar junto de companhias que não bebem em excesso. Você descobrirá um conjunto grande de novas oportunidades de se divertir. ", "Dica 17"),
("Evite lugares, pessoas e alimentos fortemente associados ao uso de álcool. Evitando este tipo de situação você aumenta as suas chances de beber menos.", "Dica 18"),
("Fique alerta ! Caso estiver precisando de quantidades maiores do que anteriormente para sentir os mesmos efeitos do álcool, isso aponta para um problema importante, mas que pode ser resolvido caso você tente parar de beber, ao menos por um tempo.", "Dica 19"),
("Preste atenção aos comentários de outras pessoas sobre seus hábitos de consumo – elas  podem estar certas quando comentam sobre o seu excesso em relação ao álcool.", "Dica 20"),
("Não desista das suas metas, quanto mais persistimos, maiores são as nossas chances de sucesso. Continue no caminho de beber menos,  caso você tenha cometido algum deslize,  utilize esta ocasião como uma lembrança do quanto é importante que você continue bebendo menos.", "Dica 21"),
("Evite manter bebidas alcoólicas em casa. Procure, ao invés disso, manter sucos, refrigerantes ou outras bebidas sem álcool para que você possa consumir em momentos que tiver vontade.", "Dica 22"),
("Se você sentir uma forte vontade de beber, tente fazer algum exercício em vez de beber - você vai se sentir melhor", "Dica 23"),
("Use pelo menos seis goles para esvaziar o seu copo. Isso cria uma regra que fará com que você demore mais tempo para esvaziar o seu copo, bebendo menos como consequência.", "Dica 24"),
("Evite bebidas alcoólicas e principalmente, evite misturar diferentes tipos de bebidas. Quando você mistura diferentes tipos de bebidas é mais difícil contar e planejar o número de doses que você irá tomar.", "Dica 25"),
("Acesse o seu diário eletrônico sempre que você sentir vontade de beber, e considere os objetivos que você definiu.  Lembrar das suas metas será sempre muito útil  ", "Dica 26"),
("Evite consumir álcool para relaxar, tente encontrar alternativas, tais como exercícios e hobbies. ", "Dica 27"),
("Querendo beber menos ? Procure seguir as estratégias de redução que melhor se adequem a você. ", "Dica 28"),
("Quando o seu copo está vazio, pense nas conseqüências de beber um pouco mais. Ir além das doses que você planejou pode fazer com que venha a ter problemas em controlar o seu consumo", "Dica 29"),
("Pessoas que realmente gostam de você, continuarão ao seu lado mesmo que opte por beber menos. Você não precisa beber para estar com os seus amig@s", "Dica 30"),
("Sempre registre quantas vezes e quanto você bebe durante uma semana.  Evite beber \"automaticamente\", sem perceber o quanto você está bebendo.  Contar a quantidade de bebida que você consome é a melhor maneira de conseguir atingir sua meta de beber menos.", "Dica 31"),
("Reduzir seu consumo de álcool pode não ser uma tarefa tão fácil, mas caso você se esforce para alcançar este objetivo, terá maiores chances de ser bem sucedido.", "Dica 32"),
("Aprenda que é um direito seu recusar uma bebida, quando alguém lhe oferece. Diga sempre não,  muito obrigado ! Esta fórmula é simples e pode ajudar em diversas situações. ", "Dica 33"),
("Se você quiser parar de beber, mas têm encontrado dificuldades fazendo isso, procure um profissional de saúde que pode ajudar. Pedir ajudar pode ser um passo difícil, mas que trará recompensas importantes no futuro.", "Dica 34"),
("Se você gastar muito tempo bebendo, pense em alternativas melhores: como o que fazer com sua família, pais e amigos", "Dica 35"),
("Ainda que estiver bebendo menos, nunca dirija após beber. Pensar em sua saúde, também envolve pensar em evitar acidentes", "Dica 36"),
("Sempre pense nas conseqüências e em sua saúde antes de começar a beber. Crie este hábito de pensar sobre as consequências antes de começar a beber. ", "Dica 37"),
("Não beba com o estômago vazio. Sempre faça uma boa refeição antes de começar a beber, isso ajudará você a beber menos. ", "Dica 38"),
("Evite estar na companhia de pessoas com quem você costuma beber muito. Isso pode ser difícil no início, mas poderá contribuir muito para que alcance a sua meta de beber menos.", "Dica 39"),
("Lembre-se sempre de comentar e pedir apoio para beber menos aos seus colegas, amigos e familiares.  Quando dividimos nossos problemas é mais fácil de enfrentarmos nossas dificuldades", "Dica 40"),
("Pratique como dizer NÃO de forma simples. Você não precisa de longas explicações para evitar beber em situações que as pessoas lhe pressionam. ", "Dica 41"),
("Evite a participação em jogos de beber ou concursos. Muitas vezes estes jogos envolvem grandes quantidades de bebida, consumidas de maneira muito rápida, potencializando problemas decorrentes do consumo.", "Dica 42"),
("Quando você for a uma festa ou a um show evite beber antes de chegar neste lugar.  Beber antes da festa pode aumentar as suas chances de ter problemas durante a festa.", "Dica 43"),
("Evite atividades sociais que envolvem beber. Evite principalmente àqueles que são voltadas exclusivamente para o consumo de bebidas alcoólicas.", "Dica 44"),
("Um exercício que pode lhe ajudar é evitar dar o primeiro gole.  Espere em torno de 1 ou 2 horas para começar a beber, este tempo pode lhe ajudar a controlar a vontade de beber e a pensar nas consequencias negativas do consumo.", "Dica 45"),
("Evite beber antes ou durante o café da manhã. Caso sinta muita vontade ou necessidade de beber pela manhã procure a ajuda de um profissional que possa ajudá-lo. ", "Dica 46"),
("Lembre-se de comer antes e/ou durante o momento que está bebendo. Quanto melhor alimentado, menores são as suas chances de beber em maiores quantidades.", "Dica 47"),
("Decida sobre os seus limites e não os ultrapasse. Essa é uma regra de ouro, que pode lhe ajudar bastante.", "Dica 48"),
("Evite participar de rodadas. Estas ocasiões podem contribuir para que você consuma álcool para além do que havia planejado.", "Dica 49"),
("Não desista se você não for capaz de atingir seus objetivos na primeira tentativa. Continuar tentando é o passo mais importante !", "Dica 50"),
("Não se preocupe caso em algum momento você consuma mais do que o planejado. Entenda isso como um sinal de que você ainda precisa persistir na sua meta", "Dica 51"),
("Quando você perceber os primeiros sinais de que está ficando tonto por beber, faça uma pausa. Peça para um amigo para lembrá-lo disso. ", "Dica 52"),
("A melhor maneira de evitar uma ressaca é bebendo menos. A ressaca indica que seu organismo está intoxicado pelo álcool e que está exposto à prejuízos para a sua saúde ", "Dica 53"),
("Tome bastante água antes de alguma bebida alcoólica. Considere esta dica, especialmente se você está com sede. ", "Dica 54"),
("Identifique as coisas/imagens/pensamentos que contribuem para o seu bem-estar. Muitas pessoas exageram com o álcool por estarem tristes ou com raiva. ", "Dica 55"),
("Inclua uma atividade física de lazer em alguma parte do seu dia. Atividades físicas além de contribuem para a sua saúde podem ajudar você no processo de beber menos ", "Dica 56"),
("Procure desenvolver algum hobby que mantenha você interessado e ocupado nos momentos livres. Essa é uma estratégia boa para ocupar o dia e ajudá-lo a se sentir melhor. ", "Dica 57"),
("Tente fazer exercícios de respiração ou alguma forma de relaxamento todos os dias. Buscar momentos no seu dia para relaxar, pode ter um impacto positivo para a sua saúde.", "Dica 58"),
("Evite ficar próximo de bares, restaurantes ou cafés que servem álcool. Estes locais podem fazer com que você sinta mais vontade de beber.", "Dica 59"),
("Não se esqueça de se recompensar, mesmo por pequenas mudanças positivas. A cada dia e a cada semana que você conseguir atingir as suas metas, aproveite para se recompensar, através de pequenos agrados feitos a você mesmo. ", "Dica 60"),
("O stress pode ser uma grande desculpa para consumir mais álcool. Encontre coisas que ajudam a reduzir o seu stress e que não envolva o consumo de álcool.", "Dica 61"),
("Envolva um amigo ou membro da família em que você confia para ajudá-lo a permanecer motivado. Compartilhe com esta as metas que conseguiu alcançar e também os momentos de dificuldade", "Dica 62"),
("Fale com um amigo ou membro da família, quando você sente a necessidade de beber", "Dica 63"),
("Beba sempre muita água.  Manter-se hidratado pode ajudar a reduzir a sua vontade de beber álcool.", "Dica 64"),
("Mantenha-se com pensamentos positivos. Procure visualizar uma vida mais saudável e com mais qualidade de vida", "Dica 65"),
("Lembre-se de seu objetivo a cada dia.  Acredite que você pode atingir seus objetivos", "Dica 66"),
("Estabeleça metas realistas.  Ser muito ambicioso, querer uma mudança muito brusca pode ser menos vantajoso do que uma mudança gradual e contínua", "Dica 67");

